/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Blue Spirit (https://sketchfab.com/Blue-Spirit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/female-spartan-46770ed1e2de4de292093c635cf5e473
Title: Female Spartan
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei"

import spartanScene from '../assets/3d/spartan.glb'

const Spartan = (props) => {
    const spartanRef = useRef()
  const { nodes, materials } = useGLTF(spartanScene);
  return (
    <group ref={spartanRef}{...props}>
      <group scale={0.01}>
        <group
          position={[-13.085, -6.815, -0.047]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_Ground_0.geometry}
            material={materials.Ground}
          />
          <group
            position={[0.033, -0.034, 1.31]}
            rotation={[0.094, 0.169, -0.092]}
            scale={0.75}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eye_Eye_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eye_Cornea_0.geometry}
              material={materials.Cornea}
            />
          </group>
          <group position={[0.056, 0, 0.065]} scale={0.75}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Model001_Skin_0.geometry}
              material={materials.Skin}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Model001_Head_0.geometry}
              material={materials.Head}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Model001_teeth_0.geometry}
              material={materials.teeth}
            />
          </group>
          <group
            position={[0.061, 0.009, 1.301]}
            rotation={[0.089, 0.159, -0.082]}
            scale={0.75}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eye001_Eye_Injured_0.geometry}
              material={materials.Eye_Injured}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eye001_Cornea_0.geometry}
              material={materials.Cornea}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Eyelash_Eyelash_0.geometry}
            material={materials.Eyelash}
            position={[0.056, 0, 0.065]}
            scale={0.75}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shield_Shield_0.geometry}
            material={materials.Shield}
            position={[0.186, 0.079, 0.694]}
            rotation={[1.334, 0.048, 1.643]}
            scale={0.75}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Spear_Spear_0.geometry}
            material={materials.Spear}
            position={[0.001, -0.376, 0.619]}
            rotation={[2.03, 0.656, -1.552]}
            scale={0.843}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Braw_Outfit_0.geometry}
            material={materials.Outfit}
            position={[0.056, 0, 0.065]}
            scale={0.75}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hood_Clean_0.geometry}
            material={materials.Clean}
            position={[0.056, 0, 0.065]}
            scale={0.75}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Skirt_Outfit_0.geometry}
            material={materials.Outfit}
            position={[0.056, 0, 0.065]}
            scale={0.75}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Skirt_Tails_Outfit_0.geometry}
            material={materials.Outfit}
            position={[0.056, 0, 0.065]}
            scale={0.75}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Fabric-low_Outfit_0"].geometry}
            material={materials.Outfit}
            position={[0.056, 0, 0.065]}
            scale={0.75}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hand_Wrap_Outfit_0.geometry}
            material={materials.Outfit}
            position={[0.056, 0, 0.065]}
            scale={0.75}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Earings_Outfit_0.geometry}
            material={materials.Outfit}
            position={[0.056, 0, 0.065]}
            scale={0.75}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Armor_low_Body_Armor_0.geometry}
            material={materials.Body_Armor}
            position={[0.056, 0, 0.065]}
            scale={0.75}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boots_Body_Armor_0.geometry}
            material={materials.Body_Armor}
            position={[0.056, 0, 0.065]}
            scale={0.75}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RH002_Body_Armor_0.geometry}
            material={materials.Body_Armor}
            position={[0.056, 0, 0.065]}
            scale={0.75}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.ParticleSystem_ParticleSystem_Texture_Region001_0.geometry
          }
          material={materials["ParticleSystem_Texture_Region.001"]}
          position={[-7.49, -0.322, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={75.007}
        />
      </group>
    </group>
  );
}

export default Spartan
